### ISSUE TITLE
[Registration request] - Illuminate Security Pty Ltd.

### ISSUE THREAD

**Issue by shaunvlassis** [shannaniggans/cyberanode#1]
## To register, companies must meet the following criteria:

* Deliver cybersecurity products or services, category definitions can be [found here](categories.md)
* Hold a valid Australian Business Number (ABN), operate in Australia, and employ staff in an Australian location.

***

### Company Details

- [ABN 50 653 011 833] **Australian Business Number (ABN):**
- [Illuminate Security] **Legal Business Name or Trading Name:**
- [PO Box 470 Concord NSW 2137] **Trading Address:**
- [contact@illuminatesecurity.com] **Public Enquiries Email:**
- [N/A] **Contact Phone Number (if applicable)::**
- [www.illuminatesecurity.com] **Website:**
- [Shaun Vlassis] **Owner/CEO and/or Managing Director's Contact Details:**
- [Shaun Vlassis] **Preferred Contact Person:**
- [Attached.] **Company Logo attached**
<img width="829" alt="logo" src="https://github.com/shannaniggans/cyberanode/assets/1410898/fcdabc81-0dc1-40a9-a37f-e00cc8cbd937">

## Organisation Profile

- [N/A] **Parent Company Name and Location (if applicable):**
- [Privately Listed] **Public or Privately Listed:**
- [2-10] **Number of Full-Time Equivalent (FTE) Employees in Australia:**
- [We help organisations solve complex security operations challenges with novel and unique products and solutions.] **Short Bio Describing Your Business (max. 1,000 characters):**
- [We are the pioneers in community powered managed detection & response services. Through detection bounty programs your organisation can achieve scalable, reliable, effective and sustainable cyber threat detection capabilities. ] **Short Description of Your Business Solutions Offered (max. 1,000 characters):**

***

The following is information about the products and services that you provide.

### [Bluehat Platform][https://www.illuminatesecurity.com/bluehat-platform]
Product_category: Detection Bounty Platform 
Product description, maximum 50 words: The worlds leading Detection Bounty Program Platform enabling organisations to gain access to the expertise needed to defend themselves and proactively identify adversaries.

### [Crowd Powered Managed Detection & Response][https://www.illuminatesecurity.com/platform-use-cases]
Service_category: Crowd Powered Managed Detection & Response
Service description, maximum 50 words.: Managed Detection & Response with the power of the largest trusted community of security experts.

***
If you resell products or services, you can add them here, please use this format so we can easily create the tags:

reseller: [
    ""
]

***

## Submission Guidelines

- [x] Ensure all required information is filled in accurately.
- [x] Attach company logo image files.
- [x] Provide concise and informative descriptions within character limits.
- [x] Select appropriate options from the lists provided.

## Additional Notes

- [ ] Any additional notes or comments for the CyberAnode team.

**Comment by shannaniggans** [comment]
Company page [created](https://github.com/shannaniggans/cyberanode/blob/main/pending-company-listing/illuminate_security/illuminate_security.md)

Please review and let me know any changes.

**Comment by shannaniggans** [comment]
@vlashef checked and we are good to roll.
