### ISSUE TITLE
[Registration request]

### ISSUE THREAD

**Issue by pamoshea** [shannaniggans/cyberanode#2]
## To register, companies must meet the following criteria:

* Deliver cybersecurity products or services, category definitions can be [found here](categories.md)
* Hold a valid Australian Business Number (ABN), operate in Australia, and employ staff in an Australian location.

***

### Company Details

- [ ] **Australian Business Number (ABN):** 78 623 208 499 
- [ ] **Legal Business Name or Trading Name:** Shea Security
- [ ] **Trading Address:** Level 4, 152 Elizabeth Street, Melbourne, VIC, 3000
- [ ] **Public Enquiries Email:** contact@sheasecurity.com.au
- [ ] **Contact Phone Number (if applicable)::** 
- [ ] **Website:** https://sheasecurity.com.au/
- [ ] **Owner/CEO and/or Managing Director's Contact Details:** Dr. Pamela O'Shea
- [ ] **Preferred Contact Person:** Dr. Pamela O'Shea
- [ ] **Company Logo attached** 
![logoHorizont](https://github.com/shannaniggans/cyberanode/assets/25950904/88484f52-e046-499c-9572-4006b9984570)

## Organisation Profile

- [ ] **Parent Company Name and Location (if applicable):**
- [ ] **Public or Privately Listed:** Private
- [ ] **Number of Full-Time Equivalent (FTE) Employees in Australia:** 5
- [ ] **Short Bio Describing Your Business (max. 1,000 characters):** Based in Melbourne and founded in 2018. Our work involves testing the security of computer systems, applications and networks. Additionally, we provide education and training to software developers and IT professionals based on our testing and research. We have considerable experience in penetration testing (pentesting) for some of Australia's most widely known companies. This includes working closely with security engineers and managers as they continuously adjust and improve the security of their systems.
- [ ] **Short Description of Your Business Solutions Offered (max. 1,000 characters):**
* Black box testing
* White box testing / source code review
* Web application testing
* Application Program Interface (API) testing
* Mobile application testing
* Internal network testing
* Perimeter testing and monitoring of externally facing assets
* Cloud testing
* PCI testing
* Physical products including IOT and embedded devices
* Security training for developers
* Security awareness training
* Security culture programs

***

The following is information about the products and services that you provide.

### [Penetration Testing](https://sheasecurity.com.au)
Service_category: Penetration Testing 

### [Security Training](https://sheasecurity.com.au)
Service_category: Security Training

## Submission Guidelines

- [x] Ensure all required information is filled in accurately.
- [x] Attach company logo image files.
- [x] Provide concise and informative descriptions within character limits.
- [x] Select appropriate options from the lists provided.

## Additional Notes

- [ ] Any additional notes or comments for the CyberAnode team.

**Comment by shannaniggans** [comment]
Information added to the site [here](https://github.com/shannaniggans/cyberanode/blob/main/pending-company-listing/Shea_security/shea_security.md).

Please check and let me know any changes @pamoshea else just reply here with the go ahead to publish.

**Comment by shannaniggans** [comment]
moving to company listings
