### ISSUE TITLE
[Registration request] - Proactive Labs

### ISSUE THREAD

**Issue by ProactiveMatt** [shannaniggans/cyberanode#5]
## To register, companies must meet the following criteria:

* Deliver cybersecurity products or services, category definitions can be [found here](categories.md) (Tick)
* Hold a valid Australian Business Number (ABN), operate in Australia, and employ staff in an Australian location. (Tick)

***

### Company Details

- [x] **Australian Business Number (ABN):** 15 665 297 432 
- [x] **Legal Business Name or Trading Name:** PROACTIVE LABS PTY LIMITED
- [x] **Trading Address:** Suite 78 M Centre 11 Palmerston Lane Manuka ACT 2603
- [x] **Public Enquiries Email:** info@proactivelabs.com
- [x] **Contact Phone Number (if applicable):** 02 8599 7166 
- [x] **Website:** www.proactivelabs.com 
- [x] **Owner/CEO and/or Managing Director's Contact Details:** Matthew Belvedere
- [x] **Preferred Contact Person:** Matthew Belvedere
- [x] **Company Logo attached**: (below)

![Proactive_Main_Logo_cropped](https://github.com/shannaniggans/cyberanode/assets/130980261/3c3f9543-7cee-49d2-bc42-87518c1037d3)

## Organisation Profile

- [x] **Parent Company Name and Location (if applicable):** N/A - Independent 
- [x] **Public or Privately Listed:** Private
- [x] **Number of Full-Time Equivalent (FTE) Employees in Australia:** 6
- [x] **Short Bio Describing Your Business (max. 1,000 characters):** 
Proactive Labs is a boutique cyber security company, offering a different perspective on cyber issues. We aim to help our clients in their domain, by offering our experience in ours. We are highly skilled and experienced cybersecurity professionals offering comprehensive, yet boutique cybersecurity services to businesses and organisations. With extensive professional experience, we possess an in-depth understanding of the dynamic Canberra market. To cater to its specific and unique needs, we offer tailored and customised solutions. We provide services such as penetration testing, threat emulation, code review, and bespoke research.

- [x] **Short Description of Your Business Solutions Offered (max. 1,000 characters):**

* Penetration Testing
* Web application penetration testing
* Application Programmer Interface (API) penetration testing
* Infrastructure penetration testing
* External/Internal network penetration testing
* Mobile assessment penetration testing
* Standard Operating Environment (SOE) assessments
* Code Review
* Red Team engagements

***

The following is information about the products and services that you provide.

### [Penetration Testing](https://www.proactivelabs.com.au/services/index.html)
Product_category: penetration testing

***
If you resell products or services, you can add them here, please use this format so we can easily create the tags:

reseller: [
    "Company A",
    "Company B",
]

(N/A)
***

## Submission Guidelines

- [x] Ensure all required information is filled in accurately.
- [x] Attach company logo image files.
- [x] Provide concise and informative descriptions within character limits.
- [x] Select appropriate options from the lists provided.

## Additional Notes

- [x] Any additional notes or comments for the CyberAnode team.

**Comment by shannaniggans** [comment]
page created, please review and let me know if its good to go - https://github.com/shannaniggans/cyberanode/blob/main/pending-company-listing/proactive_labs/proactive_labs.md

**Comment by ProactiveMatt** [comment]
confirming - looks good to me! happy to proceed

**Comment by shannaniggans** [comment]
Moving to company listing
